// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230615143451_seeding2.0")]
    partial class seeding20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24d9cfb9-6263-48ab-815b-a8099e4d1984"),
                            Content = "Hello world! I am using this website for the first time and im hoping that i can make some friendse here! :D",
                            Title = "This is my first post! Wooo!"
                        },
                        new
                        {
                            Id = new Guid("56e6c087-bf00-4dcc-bddd-ad097cc94fbe"),
                            Content = "Hello friends! I am asking for some help on a problme I have been having for the past couple of days because i just can't seem to find a suitable solution...",
                            Title = "Hello there!"
                        },
                        new
                        {
                            Id = new Guid("34bfb7db-d393-46af-bde2-acd9efd525d6"),
                            Content = "Thank you guys! What you've all said has really helped me overcome my problem and im so grateful to be on this site with such amazing people!",
                            Title = "Thanks!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
